title : API Evangelist Reading List

safe: true
lsi: false
pygments: true
auto: true

source: reading-list
destination: reading-list

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 250
paginate_path: "/blog/page:num"

production_url : http://reading-list.apievangelist.com

BASE_PATH : http://reading-list.apievangelist.com

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
